/**
 * Map of common Indian lender/vendor names → their primary domain.
 * Used to resolve the Google favicon endpoint URL at EMI creation time.
 * Keys are lowercased for case-insensitive matching.
 */
export const LENDER_MAP: Record<string, string> = {
  'moneyview': 'moneyview.in',
  'bajaj finserv': 'bajajfinserv.in',
  'bajaj': 'bajajfinserv.in',
  'hdfc bank': 'hdfcbank.com',
  'hdfc': 'hdfcbank.com',
  'icici bank': 'icicibank.com',
  'icici': 'icicibank.com',
  'idfc first': 'idfcfirstbank.com',
  'idfc first bank': 'idfcfirstbank.com',
  'idfc': 'idfcfirstbank.com',
  'navi': 'navi.com',
  'kreditbee': 'kreditbee.in',
  'sbi': 'sbi.co.in',
  'state bank of india': 'sbi.co.in',
  'axis bank': 'axisbank.com',
  'axis': 'axisbank.com',
  'kotak': 'kotak.com',
  'kotak mahindra bank': 'kotak.com',
  'tata capital': 'tatacapital.com',
  'tata': 'tatacapital.com',
  'pnb': 'pnbindia.in',
  'punjab national bank': 'pnbindia.in',
  'hero fincorp': 'herofincorp.com',
  'l&t finance': 'ltfs.com',
  'muthoot finance': 'muthootfinance.com',
  'muthoot': 'muthootfinance.com',
  'home credit': 'homecredit.co.in',
  'indusind bank': 'indusind.com',
  'indusind': 'indusind.com',
  'yes bank': 'yesbank.in',
  'yes': 'yesbank.in',
  'federal bank': 'federalbank.co.in',
  'federal': 'federalbank.co.in',
  'early salary': 'earlysalary.com',
  'fibe': 'fibe.in',
  'cashe': 'cashe.co.in',
  'prefr': 'prefr.com',
  'paysense': 'paysense.in',
  'capital float': 'capitalfloat.com',
  'lendingkart': 'lendingkart.com',
  'incred': 'incred.com',
  'stashfin': 'stashfin.com',
  'ring': 'ring.capital',
  'slice': 'sliceit.com',
  'uni cards': 'uni.cards',

  // Common Expense Vendors
  'swiggy': 'swiggy.com',
  'zomato': 'zomato.com',
  'amazon': 'amazon.in',
  'flipkart': 'flipkart.com',
  'blinkit': 'blinkit.com',
  'zepto': 'zeptonow.com',
  'uber': 'uber.com',
  'ola': 'olacabs.com',
  'rapido': 'rapido.bike',
  'jio': 'jio.com',
  'airtel': 'airtel.in',
  'vi': 'myvi.in',
  'myntra': 'myntra.com',
  'ajio': 'ajio.com',
  'bigbasket': 'bigbasket.com',
  'dunzo': 'dunzo.com',
  'swiggy instamart': 'swiggy.com',
  'cred': 'cred.club',
  'paytm': 'paytm.com',
  'phonepe': 'phonepe.com',
  'google pay': 'pay.google.com',
  'gpay': 'pay.google.com',
  'bhim': 'bhimupi.org.in',
  'freecharge': 'freecharge.in',
  'mobikwik': 'mobikwik.com',
  'netflix': 'netflix.com',
  'prime video': 'primevideo.com',
  'hotstar': 'hotstar.com',
  'disney+ hotstar': 'hotstar.com',
  'spotify': 'spotify.com',
  'youtube premium': 'youtube.com',
  'apple music': 'apple.com',
  'sony liv': 'sonyliv.com',
  'zee5': 'zee5.com',
  'bookmyshow': 'bookmyshow.com',
  'makemytrip': 'makemytrip.com',
  'goibibo': 'goibibo.com',
  'yatra': 'yatra.com',
  'cleartrip': 'cleartrip.com',
  'irctc': 'irctc.co.in',
  'redbus': 'redbus.in',
  'oyo': 'oyorooms.com',
  'airbnb': 'airbnb.co.in',
  'agoda': 'agoda.com',
  'booking.com': 'booking.com',
  'tata cliq': 'tatacliq.com',
  'nykaa': 'nykaa.com',
  'purple': 'purplle.com',
  'urban company': 'urbancompany.com',
  'zudio': 'zudio.com',
  'dmart': 'dmart.in',
  'reliance smart': 'reliancesmart.in',
  'spencers': 'spencers.in',
  'more': 'moreretail.in',
  'natures basket': 'naturesbasket.co.in',
  'star bazaar': 'starbazaarindia.com',
  'lifestyle': 'lifestylestores.com',
  'shoppers stop': 'shoppersstop.com',
  'pantaloons': 'pantaloons.com',
  'max fashion': 'maxfashion.in',
  'h&m': 'hm.com',
  'zara': 'zara.com',
  'decathlon': 'decathlon.in',
  'croma': 'croma.com',
  'reliance digital': 'reliancedigital.in',
  'vijay sales': 'vijaysales.com',
  'sangeetha mobiles': 'sangeethamobiles.com',
  'poorvika': 'poorvika.com',
  'ikea': 'ikea.com',
  'pepperfry': 'pepperfry.com',
  'urban ladder': 'urbanladder.com',
  'furlenco': 'furlenco.com',
  'rentomojo': 'rentomojo.com',
  'vogo': 'vogo.in',
  'bounce': 'bounceshare.com',
  'yulu': 'yulu.bike',
  'zoomcar': 'zoomcar.com',
  'revv': 'revv.co.in',
  'drivezy': 'drivezy.com',
  'mygate': 'mygate.com',
  'nobroker': 'nobroker.in',
  'housing.com': 'housing.com',
  'magicbricks': 'magicbricks.com',
  '99acres': '99acres.com',
  'lic': 'licindia.in',
  'sbi life': 'sbilife.co.in',
  'hdfc life': 'hdfclife.com',
  'icici prudential': 'iciciprulife.com',
  'max life': 'maxlifeinsurance.com',
  'policybazaar': 'policybazaar.com',
  'zerodha': 'zerodha.com',
  'groww': 'groww.in',
  'upstox': 'upstox.com',
  'angel one': 'angelone.in',
  '5paisa': '5paisa.com',
  'kuvera': 'kuvera.in',
  'indmoney': 'indmoney.com',
  'smallcase': 'smallcase.com',
  'wazirx': 'wazirx.com',
  'coindcx': 'coindcx.com',
  'coinswitch kuber': 'coinswitch.co',
  'zebpay': 'zebpay.com',
  'binance': 'binance.com',
  'dream11': 'dream11.com',
  'mpl': 'mpl.live',
  'my11circle': 'my11circle.com',
  'rummycircle': 'rummycircle.com',
  'junglee rummy': 'jungleerummy.com',
  'ludo king': 'ludoking.com',
  'bgmi': 'battlegroundsmobileindia.com',
  'free fire': 'ff.garena.com',
  'valorant': 'playvalorant.com',
  'steam': 'steampowered.com',
  'epic games': 'epicgames.com',
  'playstation': 'playstation.com',
  'xbox': 'xbox.com',
  'nintendo': 'nintendo.com',
  'ea': 'ea.com',
  'ubisoft': 'ubisoft.com',
  'rockstar games': 'rockstargames.com',
  'blizzard': 'blizzard.com',
  'riot games': 'riotgames.com',
  'activision': 'activision.com',
  '2k': '2k.com',
  'square enix': 'square-enix.com',
  'capcom': 'capcom.com',
  'sega': 'sega.com',
  'konami': 'konami.com',
  'bandai namco': 'bandainamcoent.com',
  'cd projekt red': 'cdprojektred.com',
  'bethesda': 'bethesda.net',
  'naughty dog': 'naughtydog.com',
  'insomniac games': 'insomniac.games',
  'santa monica studio': 'santamonicastudio.com',
  'guerrilla games': 'guerrilla-games.com',
  'sucker punch': 'suckerpunch.com',
  'bungee': 'bungie.net',
  'respawn': 'respawn.com',
  'infinity ward': 'infinityward.com',
  'treyarch': 'treyarch.com',
  'sledgehammer games': 'sledgehammergames.com',
  'raven software': 'ravensoftware.com',
  'high moon studios': 'highmoonstudios.com',
  'toys for bob': 'toysforbob.com',
  'beenox': 'beenox.com',
  'demonware': 'demonware.net',
  'digital legends': 'digitallegends.com',
  'solid state studios': 'solidstatestudios.com',
  'shanghai': 'shanghaistudio.com',
  'mexico': 'mexicostudio.com',
  'central tech': 'centraltech.com',
  'elsewhere entertainment': 'elsewhereentertainment.com',
  'blizzard albany': 'blizzardalbany.com',
  'proletariat': 'proletariat.com',
  'blizzard boston': 'blizzardboston.com',
  'blizzard texas': 'blizzardtexas.com',
  'blizzard irvine': 'blizzardirvine.com',
  'blizzard seoul': 'blizzardseoul.com',
  'blizzard sydney': 'blizzardsydney.com',
  'blizzard taipei': 'blizzardtaipei.com',
  'blizzard versailles': 'blizzardversailles.com',
  'blizzard cork': 'blizzardcork.com',
  'blizzard austin': 'blizzardaustin.com',
  'blizzard shanghai': 'blizzardshanghai.com',
  'blizzard tokyo': 'blizzardtokyo.com',
  'blizzard singapore': 'blizzardsingapore.com',
  'blizzard mexico city': 'blizzardmexicocity.com',
  'blizzard sao paulo': 'blizzardsaopaulo.com',
}

/**
 * Resolve a lender name to its favicon domain.
 * Returns null if the lender is not in the map.
 */
export function resolveLenderDomain(lenderName: string): string | null {
  const key = lenderName.trim().toLowerCase()
  return LENDER_MAP[key] ?? null
}

/**
 * Get Google favicon URL for a domain.
 */
export function getFaviconUrl(domain: string): string {
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=128`
}

/**
 * Generate initials (up to 2 chars) from a lender name.
 */
export function getLenderInitials(lenderName: string): string {
  return lenderName
    .trim()
    .split(/\s+/)
    .slice(0, 2)
    .map((word) => word[0]?.toUpperCase() ?? '')
    .join('')
}
